### ISSUE TITLE
Innhold i LargeCard wrapper ikke ordentlig

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-enonicxp-frontend#1093]
![image](https://user-images.githubusercontent.com/71373910/191499137-fd5ca279-e332-4f52-a6c2-70a66627c5fa.png)

https://www.nav.no/ikke-penger

**Comment by macbruker** [comment]
Ser to potensielle forslag til forbedring her. Enten at redaktør manuelt får muligheten til å legge inn myk bindestrek (`&shy;`) via redigeringsgrensesnittet, eller at vi legger inn CSS `hyphens: auto;` som håndterer tilfellene der lange ord vanligvis ikke får plass.
