### ISSUE TITLE
Forbedre title på egne navno-sider og utarbeide anbefalinger med hensyn til hvordan andre applikasjoner bør utarbeide title.

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#1106]
Ref diskusjon på Slack: https://nav-it.slack.com/archives/C9CJ794PP/p1664784703938129

Title kan med fordel ha en mer tydelig oppygging på tvers av sider og applikasjoner:
- Ikke bruke "www.nav.no" i tittelen siden dette oppleves som litt overflødig?
- Skal man bruke "Forside" eller "Startside" som default for nav.no, men endre dersom man er på forsiden for arbeidsgiver eller samarbeidspartner?
- Hvordan kan vi utarbeide føringer og anbefalinger for andre team som har egne applikasjoner på nav.no

**Comment by macbruker** [comment]
Litt på siden, men også relatert teknisk … det er mulig å optimalisere lastetid for sider basert på rekkefølgen av tags i head. Harry Roberts har en lærerik presentasjon om dette. 

[YouTube: Get Your Head Straight with HARRY ROBERTS - SmashingConf San Francisco 2022](https://www.youtube.com/watch?v=UW1PEMBdX5E)
https://speakerdeck.com/csswizardry/get-your-head-straight?slide=39

**Comment by tobiasmcvey** [comment]
Notater fra møtet 

Søkemotorer ønsker at vi har unike addresser og titler på sidene våre så de kan se forskjell på de og gi de til folk basert på søkeordene.

Beholder vi nav.no i sidetittel? Forslag å flytte den til slutten av sidetittel
Skal vi nevne målgruppe? I dagens URL-formel nevner vi ikke personbruker, kun de andre: arbeidsgiver, samarbeidspartner
Skal vi nevne inndeling av innhold? Bør vi nevne om det er lokalt innhold, området, kontorsider
