### ISSUE TITLE
Ny videovisning - statistikk Amplitude

### ISSUE THREAD

**Issue by macbruker** [navikt/nav-enonicxp-frontend#1147]
Skisse er klare og kan implementeres. Jeg hjelper gjerne til med frontend, men tror det er lurt om noen andre eier oppgaven herfra. https://delicate-sunburst-edd62f.netlify.app/video-teaser/

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1032194/201637107-f26e61de-5dac-4fc5-8502-392931df85b2.png">

### Statistikk:
- Ønsker å logge antall views, både i form av "startet video", men gjerne også finne en måte å se hvor mange som har sett 25% 50% 70% og 100% av videoen om mulig.

### Eksempler Qbrick (embed):
- https://www.nav.no/aktivitetsplan
- https://www.nav.no/okonomi-gjeld

### Eksempler Vimeo (ekstern lenke):
- https://www.nav.no/no/lokalt/oslo/nav-arbeidslivssenter-oslo/nyheter-oslo/opplaeringsvideoer (død lenke)

### Eksempler Prezi (ekstern lenke):
- https://www.nav.no/no/lokalt/oslo/nav-arbeidslivssenter-oslo/nyheter-oslo/opplaeringsvideoer/visste-du-dette-partssamarbeid

### Kommentar fra Olav på [opprinnelig oppgave](https://github.com/navikt/nav-enonicxp/issues/1298): 
"Oppgave: Lage et frimerkeikon som viser at her kan du se en video.

Kontekst: Videoer skal være supplerende sekundær-informasjon som kan berike skriftlig informasjon, og eventuelt være et alternativ til dem som ikke kan nyttiggjøre seg skriftlig informasjon.

Det visuelle elementet bør kunne brukes både for å indikere og eksponere en embedded video (som ligger hos Qbrick), eller en video som vi bare lenker til, som ligger på et annet nettsted (typisk Vimeo)"

[Diskusjon om logging og avspillingslengde (Tobias)](https://nav-it.slack.com/archives/GNP7GJU6M/p1672651701960639)

**Comment by macbruker** [comment]
Lenke til Qbrick API-dokumentasjon
https://video.qbrick.com/docs/api/#.general

**Comment by macbruker** [comment]
Eksempel på video på nav.no 
https://www.nav.no/okonomi-gjeld

**Comment by terjeofnorway** [comment]
Kikket litt på denne. Noen forslag:
- Beholde dagens video-macro for bakoverkompatibilitet.
- På XP-nivå: Destructe url'en som postes for å hente ut accountId og mediaId.
- På XP-nivå: Deretter sette opp en callback som håndterer kall mot Qbrick-apiet for å hente diverse thumbnails og nødvendig før dette returneres som en del av json til frontend.

På den måten vil vi få dette inn i cachen også.

**Comment by PerOlavM** [comment]
Ser på logging til Amplitude (ble glemt).

**Comment by PerOlavM** [comment]
Har utvidet dataene som logges ved video start:

- Tittel
- Varighet
- Språk

**Comment by PerOlavM** [comment]
Oversikt over videoavspilling og hvor lenge brukerene ser på, finnes i Qbrick:
https://video.qbrick.com/#/analytics/videoperformance
