### ISSUE TITLE
Varselsystem til redaktørene på enkelte maler om korrekt bruk

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#1176]
Enkelte maler skal ikke brukes av redaktørene generelt - kun for redaktørene i nav.no. Eksempel er nyhetsmal for presse og aktuelt-sider (?).

Siden vi ikke har noen detaljert tilgangskontroll kunne vi lagt på en banner i topp av malen ved redaktørvisning som advarer om bruk og henviser til Aksel.

**Comment by ojnybo** [comment]
Avventer på at Enonic leverer tilgangskontroll. Gjør ikke noe med dette.
