### ISSUE TITLE
Parsing-feil

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-enonicxp-frontend#1181]
WCAG 4.1.1: Parsing

Testet med validator.w3.org

- [ ] Produktside Servicehund
Gir feil "Error: Duplicate ID kort-om." Men det ser ut til å være en falsk positiv. Ser det samme på andre sider også

- [x] Produkside Tilleggsstønader
Flere tilfeller av: "Error: An img element which has an alt attribute whose value is the empty string must not have a role attribute."

- [x] Forside
Flere tilfeller av "Error: An img element which has an alt attribute whose value is the empty string must not have a role attribute.

- [x] Områdeside Pensjon
Flere tilfeller av "Error: An img element which has an alt attribute whose value is the empty string must not have a role attribute."

- [x] Oversiktsside Pengestøtter og tjenester fra A til Å
"Warning: The navigation role is unnecessary for element nav."

- [x] Oversiktsside Utbetalingsdatoer
"Warning: The navigation role is unnecessary for element nav."
"Element div not allowed as child of element span in this context."
"An img element which has an alt attribute whose value is the empty string must not have a role attribute."

- [ ] Får "Error: Bad value 2019-12-01T20:53:26.471380900Z for attribute datetime on element time: A fraction of a second must be one, two, or three digits." på flere sider. Usikker på om det er et faktisk problem, skal ta en titt på det.

- [ ] Oppdater wcag-rapport-json-filer når ferdig?

**Comment by PerOlavM** [comment]
Duplicate ID "kort-om":
Er duplisert når du velger "view-source", men er korrekt i DOM-en, og koden fungerer. 
Velger å se bort fra denne.
