### ISSUE TITLE
Starte å legge komponent(er) inn i Designsystemet

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-enonicxp-frontend#1201]
[Hvilke komponenter og for hvem?](https://nav-it.slack.com/archives/GNP7GJU6M/p1668521644332239?thread_ts=1668519932.320619&cid=GNP7GJU6M)

**Comment by ojnybo** [comment]
Ikke aktuell lenger, lager ny oppgave hvis det blir aktuelt
