### ISSUE TITLE
Avviktstekst for chat på forsiden

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-enonicxp-frontend#1205]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/71373910/212015538-9074a84c-2578-4f5a-b9b4-551b35d834b9.png">

Legge til mulighet for å legge inn en avvikstekst i chatinngangen også på forsiden. Ønske fra Tuva

[Designforslag](https://www.figma.com/file/TKycckNluVMUCZdNQJlq7m?node-id=62:263#340240174)

**Comment by chrisarnesen** [comment]
Tagger deg til design forslag i Figma @bdahle.
