### ISSUE TITLE
UU: AAA krav til linjehøyde. Bør denne settes til 1.5 i sidemenyer og andre steder der teksten kan brekke på flere linjer?

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-enonicxp-frontend#1306]

**Comment by PerOlavM** [comment]
Chris sjekker med ds om aksel kan sette linjehøyden til mimimum 1.5 for alle typografikomponenter.
Hvis ikke, vurderer vi å sette BodyLong på valgene i sidemenyene.

**Comment by ojnybo** [comment]
Avventer denne til vi får tilbakemelding fra designsystemet

**Comment by macbruker** [comment]
Om det bare er sidemenyen, tenker jeg det vi bare kan øke linje-høyden fra `var(--a-font-line-height-large)` til `var(--a-font-line-height-xlarge)` uten å vente på avklaringer.
