### ISSUE TITLE
Sjekk på duplikate anker-id fungerer ikke. Må sørge for at det ikke finnes duplikater i siden (flere maler?)

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-enonicxp-frontend#1424]

**Comment by anders-nom** [comment]
La inn et generelt varsel for duplikate id'er, som ser sånn ut:
![duplicate-id-warning](https://github.com/navikt/nav-enonicxp-frontend/assets/18137669/33f4e3ec-890f-4e56-9e0b-ed4c164604ca)
