### ISSUE TITLE
https://www.nav.no/person/skriv-til-oss gir korrupt 404-side

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-enonicxp-frontend#1480]
Sært tilfelle oppdaget av Siteimprove:
https://www.nav.no/person/skriv-til-oss redirecter til en 404-side med dobbel #maincontent

**Comment by anders-nom** [comment]
404-håndteringen for content-typer som kun skal vises i content studio er ikke helt bra. Det blir noen dupliserte nøstede elementer, feil status-kode og mer data enn nødvendig til klienten.
