### ISSUE TITLE
Innspill fra NKS til produktsidene på nav.no

### ISSUE THREAD

**Issue by jannebye** [navikt/nav-enonicxp-frontend#1498]
_Denne henvendelsen ble sendt til nav.no-redaksjonen 3. juli._ 

Hallo dere! 😊 Vi fikk en henvendelse her, som jeg lurte på om dere kunne være behjelpelige på:

 

Jeg får stadig innspill etter at vi fikk nye sider på foreldrepenger om at det er vanskelig for bruker å navigere her. Det er veldig mye informasjon på siden, men det eneste man kan linke direkte til, er inndelingene på menyen til venstre. 
Hvis jeg f.eks. veileder en far der mor ikke har foreldrepenger, og skal vise ham til nav.no, må jeg skrive slik:

Du kan lese mer her: nav.no/foreldrepenger#hvor-lenge (Du må huke av for "Bare far eller medmor har rett til foreldrepenger, men har ikke aleneomsorg" for å få informasjon tilpasset din situasjon).

Hvis mor er ufør, må vi skrive slik:

Du kan lese mer her: nav.no/foreldrepenger#hvor-lenge (Du må huke av for "Bare far eller medmor har rett til foreldrepenger, men har ikke aleneomsorg", og så bla ned til du kommer til overskriften "Hva hvis mor har uføretrygd".)

Vi ønsker oss en direktelink til disse tilfellene her:

bilde

Og til underinndelingen "Hva hvis mor har uføretrygd?"

Jeg vil tro denne produktsiden er en av de sidene på nav.no med mest informasjon. Vi er veldig glade for all informasjon som er der, men det er jo viktig at bruker kan finne fram til den. Jeg har meldt dette inn til Team foreldrepenger, men de viser til at de har disse "malene" på nav.no som de må forholde seg til. Jeg er usikker på hvorvidt de tar ønskene våre om slike direktelinker videre. 

Derfor håpte jeg at dere kan ta dette via deres kontakter? 😊

 

Ser dere en mulighet for å kunne utbedre dette noe? 😊

Ønsker dere uansett en fin dag videre!

 
 
Med vennlig hilsen
Magnus

**Comment by TuvaSverdstad** [comment]
Det kunne kanskje løses med ankerlenker til disse overskriftene? Men de er jo ikke så enkle å hente ut for NKS, så vi burde kanskje se på mekanismer for å kopiere lenker til underoverskrifter etterhvert?

**Comment by jannebye** [comment]
Ja, tror det kan være lurt.

**Comment by TuvaSverdstad** [comment]
I første omgang kunne vi kanskje sjekket at de har ankerlenker og kommunisert til NKS hva de er, så de kan bruke dem om de ønsker?
