### ISSUE TITLE
Bruke cdn.nav.no for statiske ressurser i /public mappa

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-enonicxp-frontend#1561]
https://github.com/nais/frontend-plattform

**Comment by terjeofnorway** [comment]
Denne saken er også relatert: https://github.com/navikt/team-navno/issues/111

Vi hoster ikoner for Chatbot som vi forsøker å få de til å legge over på sin egen cdn. Det har vært litt trådt å få til, så spørsmålet er om vi skal få chatbot-assets ut av verden før vi legger resterende ikoner over på cdn?

**Comment by terjeofnorway** [comment]
Etter å ha kikket litt på dette er jeg usikker på om det er mer jobb enn vi har nytte av det. Bundle ligger allerede i CDN, og når vi får vekk chatbot-assets sitter vi igjen med noen få svg'er. Disse er ikke versjons-hashet, så før vi kan deploye til CDN må vi begynne å hasje disse med versjoner.

Legger tilbake, så kan vi ta en prat på Teknisk Person om det er verdt å kaste seg uti dette.
