### ISSUE TITLE
Bruk av control + F for å utvide paneler på oversiktsidene

### ISSUE THREAD

**Issue by jannebye** [navikt/nav-enonicxp-frontend#1569]
Det er mulig å bruke Control + F for å åpne alle paneler på en produktside, men det fungerer ikke for oversiktsidene. Kan det ev. fikses? Det kan være kjekt med tanke på blant annet oversettelser, det er i hvert fall det funksjonaliteten brukes for på produktsidene. Hvis det ikke er mulig, kan vi bruke elements = document.getElementsByClassName('navds-accordion__header');for(let i=0;i<elements.length;i++){elements[i].click()}  til å utvide panler-

**Comment by ojnybo** [comment]
Lukker denne.
