### ISSUE TITLE
Skjemadetaljer lastes ikke inn på nytt når bruker bytter språk på skjemaoversikter

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-enonicxp-frontend#1609]

**Comment by terjeofnorway** [comment]
@anders-nom Jeg greier ikke gjenskape denne. Har forsøkt både [Utbetalingsdatoer](https://www.nav.no/utbetalingsdatoer) og [Saksbehandlingstider](https://www.nav.no/saksbehandlingstider).

Kan du legge inn steg for å gjenskape, så kan jeg ta en titt videre?

**Comment by anders-nom** [comment]
Det gjelder kun skjemaoversikter. Er ikke live i prod ennå, men her f.eks: https://www.ekstern.dev.nav.no/soknader/en

Åpne ett av elementene som har norsk tittel og bytt til norsk språk for å gjenskape. Problemet er at array key'ene ikke eksplisitt er unike for hver språkversjon. Det vil neppe være noe problem i praksis for engelsk <-> norsk når alt er oversatt, men for norsk <-> nynorsk er det mulig at key'ene kan være like (de er utledet fra title-feltene).

De "gamle" oversiktssidene tar høyde for språk allerede, så skal ikke være noe problem der. Må bare få inn samme løsning for array keys på skjemaoversiktene.
