### ISSUE TITLE
Spesielle åpningstider og avvikstekst på kontaktmodul

### ISSUE THREAD

**Issue by jannebye** [navikt/nav-enonicxp-frontend#1625]
Når du legger inn spesielle åpningstider og avvikstekst på https://portal-admin-dev.oera.no/admin/tool/com.enonic.app.contentstudio/main/default/edit/02250637-f3d2-49ec-b024-303544b37ac8, så forsvinner teksten om åpent nå/stengt nå. 
Dette er vel en bug? 
Skjermdump 1. Viser tomt avviksfelt og da vises åpent nå.
![Image](https://github.com/navikt/nav-enonicxp-frontend/assets/37075220/e4cc18eb-c8db-4628-8555-946711c0f917)

Skjermdump 2. Viser avvviksfelt med tekst og da forsvinner åpent nå. 
![Image](https://github.com/navikt/nav-enonicxp-frontend/assets/37075220/8080f15c-2415-4449-a64b-a25404b84d60)

Har også testet at samme problem gjelder for stengt nå. Og at dette ikke bare gjelder forhåndsvisningen i CS, men at samme problem gjelder for produktsidene, se feks: https://www.ekstern.dev.nav.no/tiltakspenger

**Comment by terjeofnorway** [comment]
Diskutert nærmere med Janne 29. november:
Vi har lagt inn en mer beskrivende hjelpetekst, men lar feltet for avvik fungere slik det gjør i dag hvor det kun brukes dersom det er et teknisk avvik som gjør at det ikke gir mening å vise åpningstid. For mer planlagte avvik slik som innskreket åpningstid, så bruker vi selve ingressfeltet istedet.
