### ISSUE TITLE
Utforske hvordan vi bedre kan bruke nosnippet for organisk søk i Google.

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#1796]
I dag settes nosnippets på robots-meta. Utforske hvordan nosnippet på segmentene vil fungere bedre.

Ref diskusjon på Slack:
https://nav-it.slack.com/archives/GNP7GJU6M/p1714384137021719

**Comment by bdahle** [comment]
- [ ] Svare [Elena](https://nav-it.slack.com/archives/C9CJ794PP/p1714208127995949)
