### ISSUE TITLE
Back/forward navigering fungerer ikke mellom anchor-lenker i PageNavigationMenu

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-enonicxp-frontend#1798]
Problemet ser ut til å skyldes at next router ikke spiller på lag med history.pushState som vi bruker i PageNavigationLink. Hvis vi bytter den ut med next router.push så løser det problemet, men det brekker løsningen vi har for å sette en scroll-offset på anchor target'en. Bør kanskje skrive om den løsningen litt.

**Comment by bdahle** [comment]
(Problemet oppsto når `scrollRestoration` ble satt på i next config. Denne er satt for å huske hvor man var på siden når man navigerer tilbake)

**Comment by terjeofnorway** [comment]
Er dette fortsatt en issue etter at vi fikk på plass nye maler? Såvidt jeg kan se fungerer back/forward-navigering mellom ankerlenker med mindre jeg misforstår hva som er ønsket oppførsel...

**Comment by anders-nom** [comment]
Ser ut til å være fikset i de nye malene 💯
