### ISSUE TITLE
Storybook for filter-bar

### ISSUE THREAD

**Issue by taniaholst** [navikt/nav-enonicxp-frontend#2048]

**Comment by bdahle** [comment]
Denne brukes ikke lenger. Må beholdes foreløpig pga. versjonshistorikk.

Tale foreslo å merke den som deprecated på et vis. Kalle den noe med legacy og/eller legge den i en legacy-mappe kanskje?

**Comment by talepre** [comment]
Markert den som deprekert i koden, kommer opp slik om man bruker den: 
![FilterBarDeprekert](https://github.com/user-attachments/assets/9b038061-10b9-4248-b54a-1b0bdc35e032)
