### ISSUE TITLE
Feil i piktogram

### ISSUE THREAD

**Issue by kristin-ohlckers** [navikt/nav-enonicxp-frontend#2069]
Pliktogrammet for aktivitetshjelpemidler har fått en gul sirke. Se https://www.nav.no/saksbehandlingstider

**Comment by macbruker** [comment]
Den gule streken skulle vært blå, og i sirkelen skulle det vært et blått utropstegn. Om fyllfargen i sirkelen fjernes via DevTools, blir riktig utforming synlig, selv om fargen er feil.
![Image](https://github.com/user-attachments/assets/0a6a4147-7372-45e8-b306-30742a018233)

Trolig en CSS-selector som treffer bredere enn ønsket.

**Comment by taniaholst** [comment]
Ikonet i https://www.nav.no/strategi er fikset ✅

**Comment by terjeofnorway** [comment]
Piktogrammet er byttet ut. Brukes nå kun på [Spesialtilpasset kassebil](https://www.nav.no/kassebil), og der er stylingen riktig. De andre tingene som er nevnt i denne oppgaven er gjort, så da lukker jeg denne.
