### ISSUE TITLE
Hente ut oversikt over sider som mangler eller har tom string som meta-description

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-enonicxp-frontend#2083]
Opprettet av Martin:

"Som et ledd i forbedring av navigasjon til og på Navs nettsider, synes jeg det lurt å få oversikt over meta-description på sidene våre. På siden Om Nav fant jeg en tom beskrivelse. Dette gjorde meg nysgjerrig på hvor mange andre sider som også mangler eller har tom meta-description. Et uttrekk fra Enonic eller lignende kan være nyttig læring."

**Comment by anders-nom** [comment]
Har fikset det nå slik at ren whitespace ikke er en gyldig meta-description. M-d har en fallback til displayName'et for siden (som er påkrevd), så denne skal nå alltid bli satt.

Om vi fremdeles ønsker å ta ut noe mer data fra XP om hvordan meta-description settes så er det seff mulig. 😄
