### ISSUE TITLE
Målgruppe "For undefined"

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-enonicxp-frontend#2084]
Målgruppe blir "undefined" på https://www.nav.no/hva-er-nav og https://www.nav.no/strategi 😬

 ![Image](https://github.com/user-attachments/assets/fb651171-2d99-4e7b-ae7c-4390eb2a84d4)

**Comment by bdahle** [comment]
Mangler "Annet"? Satisfies Record string eller noe?

**Comment by kristin-ohlckers** [comment]
Trenger vi å vise noe her i det hele tatt hvis målgruppe er satt til "annet"?

**Comment by kristin-ohlckers** [comment]
Det er noe rart med utlistingen av målgruppe her også: https://www.nav.no/inntektsmelding-sykepenger

**Comment by TuvaSverdstad** [comment]
> Trenger vi å vise noe her i det hele tatt hvis målgruppe er satt til "annet"?

Nei, tenker vi ikke trenger å vise noe når det ikke er satt målgruppe. Og samme for når det ikke er satt kategori på temaartikkelen slik som i https://www.nav.no/inntektsmelding-sykepenger (og så kan vi på et eller annet tidspunkt gå over temaartiklene til arbeidsgiver og se om vi skal etablere noen kategorier for disse)
