### ISSUE TITLE
Nytt forslag til høyrekolonna for artikkelmal (dagens i XP) v/Wei og Chris

### ISSUE THREAD

**Issue by theasteen** [navikt/nav-enonicxp-frontend#320]

**Comment by terjeofnorway** [comment]
Det er litt uenighet om hva denne oppgaven faktisk innebærer.
Pr nå har jeg implementert menyutseende fra venstremenyen i produktisdemalen. Ble enige om å legge denne tilbake i "in progress" og så se på hele høyremenyen + "nyttig å vite" i en større helhet får vi avgjør hvordan vi tar denne oppgaven videre.
