### ISSUE TITLE
Åpningstider: Tabell ser ikke bra ut i mobilvisning

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-enonicxp-frontend#350]
![image](https://user-images.githubusercontent.com/47320658/113685206-4a597600-96c6-11eb-9bd0-a9cdc128eddc.png)

Denne tabelltypen ser ikke helt bra ut på mobilvisning (Safari iPhone XR)
Artikkelen er avpublisert i prod, må gjenskapes i testmiljø

**Comment by PerOlavM** [comment]
Gjøre tabeller scrollbare horisontalt i artikkelmalen på denne måten: 
https://design.nav.no/designsystem/components/tabell/accessibility
