### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jksolbakken** [navikt/nav-enonicxp-frontend#351]
Hei! Vi forsøker å forenkle bygging og adm av baseimagene våre, og ønsker derfor å kun tilby major-versjoner. Dere baserer dere nå på `12.18-alpine`. Vil det være et problem for dere å bytte til versjon `12` (eller evt oppgradere til 14)? Den vil jevnlig oppdateres fra det nyeste med samme versjon på Docker Hub.  12.18 vil ikke forsvinne, men den vil ikke lenger holdes oppdatert med sikkerhetspatcher.

**Comment by anders-nom** [comment]
Hei, vi har nå tatt i bruk `12-alpine`. Det er en bug med next.js som skaper veldig mye log-støy med node 14, derfor avventer vi oppgraderingen der (https://github.com/vercel/next.js/issues/20816).
