### ISSUE TITLE
Dynamisk artikkelmal

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-enonicxp-frontend#399]
Erstatte main-article/main-article-chapter med et komponent-basert oppsett

Felter/komponenter vi trenger (?):
- [ ] Innholdstype (nyheter/pressemelding/varig innhold) - skal denne inndelingen beholdes?
- [x] Del på sosiale medier?
- [ ] Innholdsfortegnelse: Bruk eksisterende part for navigasjonsmeny, med ny styling?
- [ ] menu-list-items: Ekspanderende paneler i menyen. Kan disse gjøres mer fleksible? Ny komponent.
- [x] Faktaboks. Ny komponent.
- [ ] Nytt system for kapitler/kapittelnavigasjon. Ny komponent?
- [ ] Fragmenter (satser, utbetalingsdatoer og saksbehandlingstider)
- [ ] Ekspander/kollaps (PO Helse har spilt inn behovet den 20. oktober for sider til arbeidsgivere. Skal brukes i forbindelse med noen eksempler på hvordan man fyller ut et krav om refusjon.

**Comment by ojnybo** [comment]
Sist prioritert av nye innholdstyper. Gå gjennom behovet på nytt
