### ISSUE TITLE
Knapper i venstremeny bør få en override av styling for å passe inn.

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#519]
Dersom man setter inn en knapp i venstremenyen, så må den settes til mini og full bredde. Hvis ikke vil den bryte ut av containeren. Det er ikke gitt at redaktørene er klar over det, så vi bør vurdere en form for "fail safe" som tar kontroll på knapper som settes inn i venstremenyen.

Forslag:
- Wrapping av tekst
- Utseende ignoreres og alle knapper blir "mini" og "fullbredde"
- Kan en part i CS være bevisst på hvilken layout den ligger i slik at innstillinger for type og størrelse fjernes når den er plassert i venstremenyen?

![Screenshot 2021-08-16 at 07 34 00](https://user-images.githubusercontent.com/1443997/129515804-229314a8-7d0e-43f0-861b-bd5c6be79a39.png)

**Comment by anders-nom** [comment]
Ble løst for en tid tilbake
