### ISSUE TITLE
Endre Ditt NAV kortet på forsiden når bruker er innlogget

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-enonicxp-frontend#538]
Når man er innlogget på nav.no så endres ingen av kortene på forsiden.

Der er kortet "Logg inn på Ditt NAV", og det skaper usikkerhet for bruker om de er innlogget eller ikke.

Vi ønsker i første omgang å se på om kortet skal beholdes, og om vi skal endre hva som står der og hva vi lenker til.

I første omgang ser vi på denne enkelte problemstillingen, men vi må også begynne å planlegge hvordan vi skal bruke innlogget tilstand for å gi bedre informasjon til innbyggere. Det blir en separat diskusjon om det.

**Comment by chrisarnesen** [comment]
Arbeidsgiver (Hanna) var også interessert i tilsvarende forbedringer.

**Comment by Laier68** [comment]
Jeg dokumenterer min del av testingen her: 
https://nav-it.slack.com/archives/GNP7GJU6M/p1630923262002200

**Comment by Laier68** [comment]
Verifikasjon i produksjon
![image](https://user-images.githubusercontent.com/60879532/133030716-cd171749-80eb-4153-8c62-c3172e22995d.png)
