### ISSUE TITLE
Støtte for samisk og evt andre språk

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#544]
Ref diskusjon i standup 8. september:

Pr i dag støtter vi bokmål og engelsk i frontend slik at feks "Kopier lenke", filtertekster og andre meldinger/varsler vises i korrekt språk avhengig av hva som er valgt under Language i CS.

For å unngå språkmiks bør vi ta en diskusjon på om vi skal utvide locale til å gjelde nynorsk og samisk i tillegg. Evt om vi også skal utvide med polsk eller andre språk.

**Comment by ojnybo** [comment]
Nynorsk-støtte ordnet i https://github.com/navikt/nav-enonicxp/issues/1182 og https://github.com/navikt/nav-enonicxp/issues/1180
