### ISSUE TITLE
Legg til metadata for å skille på bruk av menyer

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-enonicxp-frontend#640]
Vi kategoriserer alle lenkeklikk idag med "navigere".

Vi trenger å kunne skille på bruk av ulike menyer på sidene som 

* Header
* Footer
* Side-meny på produktsider, f.eks [Utvidet barnetrygd](https://www.nav.no/utvidet-barnetrygd)
* Paneler og grupper med paneler for livssituasjoner som på [forsiden](https://www.nav.no/no/person)

Vi bruker både **kategori** og **komponent** idag som attributt, og vi bruker de til det samme, så vi bør holde oss til kun én av disse. Jeg foreslår å fjerne **kategori**.

Forslag 

**Trykk på lenke i header-meny**

event-navn: navigere
komponent: header
lenketekst: Ditt NAV
destinasjon: https://www.nav.no/person/dittnav/

**Trykk på lenke i footer-meny**

event-navn: navigere
komponent: footer
lenketekst: Kontakt oss
destinasjon: https://www.nav.no/person/kontakt-oss/nb

**Trykk på sidemeny på produktside**

event-navn: navigere
komponent: innholdsmeny
lenketekst: Kort om utvidet barnetrygd
destinasjon: #kort

**Comment by TuvaSverdstad** [comment]
Tenker vi kan legge til innholdsmenyen på situasjonssiden (tilsvarende innholdsmenyen på produktsiden)
