### ISSUE TITLE
UU: Forklarende tekst ikoner på kalkulator

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-enonicxp-frontend#659]
Eksempel:
https://www.nav.no/tilleggsstonader

https://my2.siteimprove.com/Inspector/1002489/A11Y/Page?pageId=35953582983&impmd=6DD5538FAB0E174F64D81B4146785183#/sia-r43/failed/dnhLajR6NXg=;YzRkY2MwYTU=

**Comment by EivindSkifjeld** [comment]
Har spurt Morten Tollefsen på UU-teamet om det skal legges inn <title>, eller om det skal brukes aria-hidden.
