### ISSUE TITLE
Flytte Themed Header til @ds-navno

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#681]
relatert til https://github.com/navikt/team-navno/issues/104 og https://github.com/navikt/nav-enonicxp-frontend/issues/1201

ThemedPageHeader er headeren som brukes på livssituasjonssider og produktsider. Som en del av målet med å flytte over enkelte gjenbrukbare komponenter til et eget navno-workspace i designsystemet skal denne flyttes over hit.

![themedpageheader](https://user-images.githubusercontent.com/1443997/150780726-2289f109-9a0f-4277-83a7-be3a5512765b.png)

https://github.com/navikt/nav-frontend-moduler/pull/1400

**Comment by ojnybo** [comment]
Ikke aktuell lenger
