### ISSUE TITLE
Meny på produktsider får intern scrollbar.

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-enonicxp-frontend#803]
Avhengig av høyde og innhold vil navigasjonsmeny (internt) få egen scrollbar. Kan fikses ved å sette høyde eller liknende?

**Comment by macbruker** [comment]
Fristet til å lukke denne med status 'Won't fix'. 

Om vi ønsker å beholde sticky sidespalte som følger med nedover ved scrolling av vinduet, ser jeg ingen løsning på intern scrollbar i menyen er høyere enn vinduet.
