### ISSUE TITLE
Taksonomi for målinger på livssituasjonsside

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-enonicxp-frontend#834]
Vi ønsker å gruppere noen målinger på bruk av livssituasjonssidene. Kan noen legge dette til?

- [x] **Bruk av lenker i innholdsseksjoner**

event-type: navigere
seksjon: innholdsseksjon

- [x] **Bruk av lenker i innholdsmenyen**

event-type: navigere
seksjon: innholdsmeny

- [x] **Bruk av "kopier lenke"-knappen**

event-type: kopier-lenke

- [x] **Bruk av lenker i varehyllen**

event-type: navigere
seksjon: varehylle

- [x] **Bruk av lenker i "andre som kan hjelpe"**

event-type: navigere
seksjon: andre som kan hjelpe

- [x] **Bruk av lenker i kontaktmodulen**

event-type: chat-åpnet
seksjon: kontaktmodul

event-type: ring oss
seksjon: kontaktmodul

- [x] **For facebook, åpningstider og tastevalg, skriv til oss og NAV-kontor i kontaktmodul**

event-type: navigere
seksjon: kontaktmodul
lenketekst: facebook, åpningstider og tastevalg, skriv til oss, nav-kontor

**Comment by PerOlavM** [comment]
Greit å legge inn lenkegruppe for innholdsfortegnelse. 
Greit å legge til komponent for kort (vil gi mulighet til å gruppere f.eks. på tilbyder).
Men hvordan legge inn kontekst som lenkegruppe for kort (og ev. lenker)? Styres fra Content Studio?
I dag er dette layouts som kan brukes til hva som helst (og dermed ikke har noen kontekst).
