### ISSUE TITLE
Oppdatere amplitude-målinger i tråd med taksonomi

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-enonicxp-frontend#862]
Vi har endret taksonomien så den skal reflektere design-systemet 

Derfor bør vi endre disse målingene i vår frontend

Fra 
"panel-ekspander" og "panel-kollaps"
Til
“accordion åpnet” og “accordion lukket”
https://github.com/navikt/analytics-taxonomy/tree/main/events/accordion%20%C3%A5pnet

https://github.com/navikt/analytics-taxonomy/tree/main/events/accordion%20lukket

Og vi bør endre logging av skjermdeling fra "navigere" til å hete
"modal åpnet” og “modal lukket”

https://github.com/navikt/analytics-taxonomy/tree/main/events/modal%20%C3%A5pnet

https://github.com/navikt/analytics-taxonomy/tree/main/events/modal%20lukket

**Comment by PerOlavM** [comment]
Løst for nav-enonicxp-frontend. 
Egen oppgave for dekoratøren.
