### ISSUE TITLE
Undersøke routing bugs

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-enonicxp-frontend#984]
Kan gjenskapes ved å refreshe en side (F5) -> klikk en link -> refresh -> trykk tilbake i browser

Mulig next.js bug, må undersøkes

**Comment by terjeofnorway** [comment]
Denne var litt annerledes enn den feilen jeg har etterforsket og funnet en forslagsvis fiks på. Jeg har lagt denne tilbake og opprettet en ny oppgave som bedre beskriver Safari-feilen jeg har jobbet med:
https://github.com/navikt/nav-enonicxp-frontend/issues/951
