### ISSUE TITLE
Forsatt feil i rapportering basert på "url" i Amplitude.

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-enonicxp-frontend#996]
Man får fortsatt registrert navigere-events på komponenter som ikke finnes på aktuell side.

Eksempel:
https://analytics.eu.amplitude.com/nav/chart/e-s8izva2?source=copy+url

**Comment by PerOlavM** [comment]
Se ev også tidligere lukket issue:
#979

**Comment by ojnybo** [comment]
Anders fiksa denne i forrige uke.

**Comment by ojnybo** [comment]
@PerOlavM Sjekk om det fortsatt er et problem

**Comment by tobiasmcvey** [comment]
Man kan bruke parameteret "platform" fra nå av og det skal være riktig. Da må grafer som bruker "url" oppdateres med "platform" som parameter.

**Comment by tobiasmcvey** [comment]
Dette ble fikset i amplitude proxy med denne PRen

https://github.com/navikt/amplitude-proxy/commit/832dabb98f729d71914748d57aa2bc947d53f8e2
